vich_uploader:
    db_driver: orm

    mappings:
        albums_image:
            uri_prefix: '%app.path.albums_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.albums_image%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: false
        artistes_image:
            uri_prefix: '%app.path.artistes_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.artistes_image%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: false

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
