vich_uploader:
    db_driver: orm

    mappings:
        albums_image:
            uri_prefix: '%app.path.albums_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.albums_image%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
