easy_admin:
  entities:
    Artiste:
      class: App\Entity\Artiste
      form:
        fields:
          - {property: 'name', label: "Nom de l'artiste"}
          - {property: 'bio', label: "Biographie"}
          - {property: 'image'}
      list:
        actions:
          - {name: 'edit', icon: 'edit', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}